apiVersion: v1
kind: ConfigMap
metadata:
  name: math-llm-config
  namespace: math-llm-system
data:
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  MODEL_PATH: "/app/models/mistral-7b-v0.1-4bit"
  MONGODB_HOST: "mongodb.math-llm-system.svc.cluster.local"
  MONGODB_PORT: "27017"
  RABBITMQ_HOST: "rabbitmq.math-llm-system.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  REDIS_HOST: "redis.math-llm-system.svc.cluster.local"
  REDIS_PORT: "6379"
  QDRANT_HOST: "qdrant.math-llm-system.svc.cluster.local"
  QDRANT_PORT: "6333"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: math-llm-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'backend'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - math-llm-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: backend
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: true
            action: keep
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            target_label: __metrics_path__
            action: replace
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            regex: ([^:]+)(?::\d+)?;(\d+)
            target_label: __address__
            replacement: $1:$2
            action: replace
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
