apiVersion: v1
kind: Secret
metadata:
  name: math-llm-secrets
  namespace: math-llm-system
type: Opaque
data:
  # These are placeholders - replace with base64 encoded actual values in production
  MONGODB_USERNAME: YWRtaW4= # "admin" in base64
  MONGODB_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk # "secure_password" in base64
  RABBITMQ_USERNAME: YWRtaW4= # "admin" in base64
  RABBITMQ_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk # "secure_password" in base64
  REDIS_PASSWORD: c2VjdXJlX3Bhc3N3b3Jk # "secure_password" in base64
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: math-llm-system
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: c2VjdXJlX2FkbWluX3Bhc3N3b3Jk # "secure_admin_password" in base64
