# Default values for math-llm-system.
# This is a YAML-formatted file.

global:
  environment: production
  namespace: math-llm-system
  domain: math-llm.example.com
  monitoring:
    domain: monitoring.math-llm.example.com
  registry: docker.io/your-organization
  
# Backend API configuration
backend:
  name: backend
  image:
    repository: math-llm-system-backend
    tag: latest
    pullPolicy: Always
  replicaCount: 3
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 1
      memory: 4Gi
    limits:
      cpu: 2
      memory: 8Gi
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

# Frontend configuration
frontend:
  name: frontend
  image:
    repository: math-llm-system-frontend
    tag: latest
    pullPolicy: Always
  replicaCount: 3
  service:
    type: ClusterIP
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 5

# MongoDB configuration
mongodb:
  name: mongodb
  image:
    repository: mongo
    tag: 6.0
  replicaCount: 1
  service:
    type: ClusterIP
    port: 27017
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi
  auth:
    enabled: true
    rootUser: admin
    # rootPassword should be provided via --set or a values file that is not committed
    rootPassword: ""

# RabbitMQ configuration
rabbitmq:
  name: rabbitmq
  image:
    repository: rabbitmq
    tag: 3-management
  replicaCount: 1
  service:
    amqp:
      port: 5672
    http:
      port: 15672
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 2Gi
  auth:
    # username and password should be provided via --set or a values file that is not committed
    username: admin
    password: ""

# Redis configuration
redis:
  name: redis
  image:
    repository: redis
    tag: 7-alpine
  replicaCount: 1
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 2Gi
  auth:
    # password should be provided via --set or a values file that is not committed
    password: ""

# Qdrant configuration
qdrant:
  name: qdrant
  image:
    repository: qdrant/qdrant
    tag: latest
  replicaCount: 1
  service:
    api:
      port: 6333
    http:
      port: 6334
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2
      memory: 4Gi

# Prometheus configuration
prometheus:
  name: prometheus
  image:
    repository: prom/prometheus
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 9090
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

# Grafana configuration
grafana:
  name: grafana
  image:
    repository: grafana/grafana
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  admin:
    # password should be provided via --set or a values file that is not committed
    password: ""

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: math-llm-tls

# Storage Configuration
storage:
  class: standard
  models:
    size: 50Gi
